# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Sat Dec 21 20:45:09 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 402)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(180, 20, 671, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(671, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Price = QtWidgets.QWidget()
        self.Price.setObjectName("Price")
        self.ticker = QtWidgets.QLineEdit(self.Price)
        self.ticker.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ticker.setFont(font)
        self.ticker.setObjectName("ticker")
        self.pushButton_2 = QtWidgets.QPushButton(self.Price)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 240, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.Price)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Price)
        self.label_5.setGeometry(QtCore.QRect(300, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Price)
        self.label_6.setGeometry(QtCore.QRect(40, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.save_as = QtWidgets.QLineEdit(self.Price)
        self.save_as.setGeometry(QtCore.QRect(280, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_as.setFont(font)
        self.save_as.setText("")
        self.save_as.setObjectName("save_as")
        self.label_7 = QtWidgets.QLabel(self.Price)
        self.label_7.setGeometry(QtCore.QRect(280, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.start_date = QtWidgets.QDateEdit(self.Price)
        self.start_date.setGeometry(QtCore.QRect(40, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_date.setFont(font)
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName("start_date")
        self.end_date = QtWidgets.QDateEdit(self.Price)
        self.end_date.setGeometry(QtCore.QRect(300, 160, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.end_date.setFont(font)
        self.end_date.setCalendarPopup(True)
        self.end_date.setDate(QtCore.QDate(2019, 12, 21))
        self.end_date.setObjectName("end_date")
        self.browse = QtWidgets.QPushButton(self.Price)
        self.browse.setGeometry(QtCore.QRect(590, 70, 51, 31))
        self.browse.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse.setIcon(icon)
        self.browse.setIconSize(QtCore.QSize(25, 25))
        self.browse.setObjectName("browse")
        self.tabWidget.addTab(self.Price, "")
        self.Fundamentals = QtWidgets.QWidget()
        self.Fundamentals.setObjectName("Fundamentals")
        self.tabWidget.addTab(self.Fundamentals, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.priceData = QtWidgets.QPushButton(self.centralwidget)
        self.priceData.setGeometry(QtCore.QRect(30, 30, 91, 81))
        self.priceData.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/price2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priceData.setIcon(icon1)
        self.priceData.setIconSize(QtCore.QSize(55, 55))
        self.priceData.setObjectName("priceData")
        self.priceData_2 = QtWidgets.QPushButton(self.centralwidget)
        self.priceData_2.setGeometry(QtCore.QRect(30, 140, 91, 81))
        self.priceData_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/fundamental_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priceData_2.setIcon(icon2)
        self.priceData_2.setIconSize(QtCore.QSize(55, 55))
        self.priceData_2.setObjectName("priceData_2")
        self.priceData_3 = QtWidgets.QPushButton(self.centralwidget)
        self.priceData_3.setGeometry(QtCore.QRect(30, 250, 91, 81))
        self.priceData_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/delta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priceData_3.setIcon(icon3)
        self.priceData_3.setIconSize(QtCore.QSize(55, 55))
        self.priceData_3.setObjectName("priceData_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.priceData, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Financial Data Dowloader", None, -1))
        self.ticker.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ticker: e.g. FB", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Download", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Ticker", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "End", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.save_as.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Select Location", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Price), QtWidgets.QApplication.translate("MainWindow", "Price Data", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Fundamentals), QtWidgets.QApplication.translate("MainWindow", "Fundamentals", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Options Data", None, -1))

import photo_rc
