# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Sat Dec 21 23:19:08 2019
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 414)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(150, 10, 671, 351))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(671, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Price = QtWidgets.QWidget()
        self.Price.setObjectName("Price")
        self.ticker = QtWidgets.QLineEdit(self.Price)
        self.ticker.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ticker.setFont(font)
        self.ticker.setObjectName("ticker")
        self.pushButton_2 = QtWidgets.QPushButton(self.Price)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 260, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.Price)
        self.label_4.setGeometry(QtCore.QRect(40, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Price)
        self.label_5.setGeometry(QtCore.QRect(300, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.Price)
        self.label_6.setGeometry(QtCore.QRect(40, 120, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.save_as = QtWidgets.QLineEdit(self.Price)
        self.save_as.setGeometry(QtCore.QRect(280, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_as.setFont(font)
        self.save_as.setText("")
        self.save_as.setObjectName("save_as")
        self.label_7 = QtWidgets.QLabel(self.Price)
        self.label_7.setGeometry(QtCore.QRect(280, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.start_date = QtWidgets.QDateEdit(self.Price)
        self.start_date.setGeometry(QtCore.QRect(40, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_date.setFont(font)
        self.start_date.setCalendarPopup(True)
        self.start_date.setObjectName("start_date")
        self.end_date = QtWidgets.QDateEdit(self.Price)
        self.end_date.setGeometry(QtCore.QRect(300, 160, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.end_date.setFont(font)
        self.end_date.setCalendarPopup(True)
        self.end_date.setDate(QtCore.QDate(2019, 12, 21))
        self.end_date.setObjectName("end_date")
        self.browse = QtWidgets.QPushButton(self.Price)
        self.browse.setGeometry(QtCore.QRect(590, 70, 51, 31))
        self.browse.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/browse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.browse.setIcon(icon)
        self.browse.setIconSize(QtCore.QSize(25, 25))
        self.browse.setObjectName("browse")
        self.progressBar = QtWidgets.QProgressBar(self.Price)
        self.progressBar.setGeometry(QtCore.QRect(40, 220, 461, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.Price, "")
        self.Fundamentals = QtWidgets.QWidget()
        self.Fundamentals.setObjectName("Fundamentals")
        self.comboBox = QtWidgets.QComboBox(self.Fundamentals)
        self.comboBox.setGeometry(QtCore.QRect(40, 140, 421, 41))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.progressBar_2 = QtWidgets.QProgressBar(self.Fundamentals)
        self.progressBar_2.setGeometry(QtCore.QRect(40, 210, 491, 21))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Fundamentals)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 250, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.ticker_2 = QtWidgets.QLineEdit(self.Fundamentals)
        self.ticker_2.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ticker_2.setFont(font)
        self.ticker_2.setObjectName("ticker_2")
        self.save_as_3 = QtWidgets.QLineEdit(self.Fundamentals)
        self.save_as_3.setGeometry(QtCore.QRect(280, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_as_3.setFont(font)
        self.save_as_3.setText("")
        self.save_as_3.setObjectName("save_as_3")
        self.browse_3 = QtWidgets.QPushButton(self.Fundamentals)
        self.browse_3.setGeometry(QtCore.QRect(590, 70, 51, 31))
        self.browse_3.setText("")
        self.browse_3.setIcon(icon)
        self.browse_3.setIconSize(QtCore.QSize(25, 25))
        self.browse_3.setObjectName("browse_3")
        self.label_8 = QtWidgets.QLabel(self.Fundamentals)
        self.label_8.setGeometry(QtCore.QRect(40, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_16 = QtWidgets.QLabel(self.Fundamentals)
        self.label_16.setGeometry(QtCore.QRect(280, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.tabWidget.addTab(self.Fundamentals, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.progressBar_6 = QtWidgets.QProgressBar(self.tab)
        self.progressBar_6.setGeometry(QtCore.QRect(40, 180, 491, 21))
        self.progressBar_6.setProperty("value", 0)
        self.progressBar_6.setObjectName("progressBar_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 250, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.ticker_6 = QtWidgets.QLineEdit(self.tab)
        self.ticker_6.setGeometry(QtCore.QRect(40, 70, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ticker_6.setFont(font)
        self.ticker_6.setObjectName("ticker_6")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(280, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(40, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.save_as_4 = QtWidgets.QLineEdit(self.tab)
        self.save_as_4.setGeometry(QtCore.QRect(280, 70, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_as_4.setFont(font)
        self.save_as_4.setText("")
        self.save_as_4.setObjectName("save_as_4")
        self.browse_4 = QtWidgets.QPushButton(self.tab)
        self.browse_4.setGeometry(QtCore.QRect(590, 70, 51, 31))
        self.browse_4.setText("")
        self.browse_4.setIcon(icon)
        self.browse_4.setIconSize(QtCore.QSize(25, 25))
        self.browse_4.setObjectName("browse_4")
        self.tabWidget.addTab(self.tab, "")
        self.priceData = QtWidgets.QPushButton(self.centralwidget)
        self.priceData.setGeometry(QtCore.QRect(30, 40, 91, 81))
        self.priceData.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/price2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priceData.setIcon(icon1)
        self.priceData.setIconSize(QtCore.QSize(55, 55))
        self.priceData.setObjectName("priceData")
        self.priceData_2 = QtWidgets.QPushButton(self.centralwidget)
        self.priceData_2.setGeometry(QtCore.QRect(30, 150, 91, 81))
        self.priceData_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/fundamental_data.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priceData_2.setIcon(icon2)
        self.priceData_2.setIconSize(QtCore.QSize(55, 55))
        self.priceData_2.setObjectName("priceData_2")
        self.priceData_3 = QtWidgets.QPushButton(self.centralwidget)
        self.priceData_3.setGeometry(QtCore.QRect(30, 260, 91, 81))
        self.priceData_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/delta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.priceData_3.setIcon(icon3)
        self.priceData_3.setIconSize(QtCore.QSize(55, 55))
        self.priceData_3.setObjectName("priceData_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.priceData, self.tabWidget)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Financial Data Dowloader", None, -1))
        self.ticker.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ticker: e.g. FB", None, -1))
        self.pushButton_2.setText(QtWidgets.QApplication.translate("MainWindow", "Download", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Ticker", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "End", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Start", None, -1))
        self.save_as.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Select Location", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Price), QtWidgets.QApplication.translate("MainWindow", "Price Data", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Calendar", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Sustainability", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Recommendations", None, -1))
        self.comboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Annual Cashflow", None, -1))
        self.comboBox.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "Quarterly Cashflow", None, -1))
        self.comboBox.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Annual Balance sheet", None, -1))
        self.comboBox.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "Quarterly Balance sheet", None, -1))
        self.comboBox.setItemText(7, QtWidgets.QApplication.translate("MainWindow", "Annual Earnings", None, -1))
        self.comboBox.setItemText(8, QtWidgets.QApplication.translate("MainWindow", "Quarterly Earnings", None, -1))
        self.comboBox.setItemText(9, QtWidgets.QApplication.translate("MainWindow", "Annual Financials", None, -1))
        self.comboBox.setItemText(10, QtWidgets.QApplication.translate("MainWindow", "Quarterly Financials", None, -1))
        self.pushButton_3.setText(QtWidgets.QApplication.translate("MainWindow", "Download", None, -1))
        self.ticker_2.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ticker: e.g. FB", None, -1))
        self.save_as_3.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Select Location", None, -1))
        self.label_8.setText(QtWidgets.QApplication.translate("MainWindow", "Ticker", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Fundamentals), QtWidgets.QApplication.translate("MainWindow", "Fundamentals", None, -1))
        self.pushButton_7.setText(QtWidgets.QApplication.translate("MainWindow", "Download", None, -1))
        self.ticker_6.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Ticker: e.g. FB", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("MainWindow", "Ticker", None, -1))
        self.save_as_4.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Select Location", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtWidgets.QApplication.translate("MainWindow", "Options Data", None, -1))

import photo_rc
